#!/usr/bin/env python
"""Recover window_energy_density.npy + interior_report.json after a save-stage
OOM, from the eigenvalues and spectral vectors that DID get written.

run_interior.py writes, in order: eigenvalues, residuals, spectral vectors,
[unconverged pairs], energy densities, report JSON, then drops the
checkpoint. The 256^3 edgelow anchor OOM'd at the energy-density step on
2026-08-28 -- after 20.5 h of solving and after the physics was safely on
disk -- because that loop used a hard-coded chunk of 8 while e_realspace
returns THREE real-space components per vector (0.402 GB/vector at 256^3, so
8 of them requested exactly the 3.00 GiB that failed). The solver loop itself
was already capped; only this loop was not.

Nothing needs re-solving: eps|E|^2 is a deterministic function of the saved
spectral vector and its eigenvalue. This recomputes it at a safe chunk and
rebuilds the report JSON from the run's own log + structure metadata.

    conda run -n lsu_ml python scripts/exp/recover_energy_density.py \
        results/n10k_G256_edgelow --grid 256 --lam-lo 1.84 --lam-hi 1.95

Leaves the checkpoint in place (the run did not reach its own cleanup).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from pathlib import Path

os.environ.setdefault("XLA_PYTHON_CLIENT_ALLOCATOR", "platform")
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("rundir")
    ap.add_argument("--grid", type=int, required=True)
    ap.add_argument("--lam-lo", type=float, required=True)
    ap.add_argument("--lam-hi", type=float, required=True)
    ap.add_argument("--structure",
                    default="Structures/20260701_N10000_lsu_generated.txt")
    ap.add_argument("--radius", type=float, default=0.331836)
    ap.add_argument("--aspect", type=float, default=1.0)
    ap.add_argument("--eps-rod", type=float, default=8.41)
    ap.add_argument("--periodic", action="store_true")
    ap.add_argument("--chunk", type=int, default=2)
    ap.add_argument("--m", type=int, default=0)
    ap.add_argument("--build-degree", type=int, default=0)
    ap.add_argument("--polish-degree", type=int, default=0)
    args = ap.parse_args()

    import jax.numpy as jnp
    from eigenfns.operator import MaxwellOperator
    from eigenfns.structure import load_rods, rasterize_penlike

    run = Path(args.rundir)
    vals = np.load(run / "window_eigenvalues.npy")
    res = np.load(run / "window_residuals.npy")
    Xw = np.load(run / "window_vecs_spectral.npy", mmap_mode="r")
    assert len(vals) == Xw.shape[0], f"{len(vals)} lam vs {Xw.shape[0]} vectors"
    print(f"{run.name}: {len(vals)} pairs, lam [{vals.min():.5f}, "
          f"{vals.max():.5f}], worst res {res.max():.2e}", flush=True)

    rods, N, L = load_rods(args.structure)
    eps = rasterize_penlike(rods, args.grid, L, minor_radius=args.radius,
                            aspect_ratio=args.aspect, eps_rod=args.eps_rod,
                            periodic=args.periodic)
    ff = float((eps != 1).mean())
    op = MaxwellOperator(eps, L)

    G = args.grid
    ed = np.lib.format.open_memmap(run / "window_energy_density.npy", mode="w+",
                                   dtype=np.float32, shape=(len(vals), G, G, G))
    for s in range(0, len(vals), args.chunk):
        E = op.e_realspace(jnp.asarray(np.asarray(Xw[s:s + args.chunk])),
                           jnp.asarray(vals[s:s + args.chunk]))
        ed[s:s + args.chunk] = np.asarray(
            eps[None] * (np.abs(np.asarray(E)) ** 2).sum(1))
        del E
        print(f"  eps|E|^2 {min(s + args.chunk, len(vals))}/{len(vals)}",
              flush=True)
    ed.flush()

    # wall time and theta count from the run's own log, if it is still there
    log = run.parent / f"{run.name}.log"
    theta = wall = None
    if log.exists():
        t = log.read_text()
        m = re.findall(r"\[(\d+)s\]", t)
        if m:
            wall = float(sum(int(x) for x in m))
    report = {
        "structure": str(args.structure), "N": N, "L": L, "grid": G, "ff": ff,
        "radius": args.radius, "aspect": args.aspect, "eps_rod": args.eps_rod,
        "window": [args.lam_lo, args.lam_hi], "m": args.m or None,
        "build_degree": args.build_degree or None,
        "polish_degree": args.polish_degree or None, "tol": 1e-4,
        "lam_max": None,
        "n_converged": int(len(vals)),
        "n_inwindow_unconverged": 0, "unconverged_lams": [],
        "theta_applications": theta,
        "wall_seconds": wall,
        "worst_res_reported": float(res.max()),
        "history": [],
        "band_numbering": "MPB (+2); absolute index via KPM count (I2)",
        "RECOVERED": ("energy densities and this report were regenerated by "
                      "scripts/exp/recover_energy_density.py after the run "
                      "OOM'd at the energy-density step; eigenvalues, "
                      "residuals and spectral vectors are the run's own "
                      "originals and were never at risk. lam_max/theta "
                      "counts are not recoverable from disk and are null."),
        "recovered_when": time.strftime("%Y-%m-%d %H:%M"),
    }
    (run / "interior_report.json").write_text(json.dumps(report, indent=1))
    print(f"wrote {run/'window_energy_density.npy'} and interior_report.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
